// Shared DB runtime. Owns a Mutex<Connection> via tauri::State.
//
// Migration enumeration is generated at build time by build.rs from
// packages/shared-db/migrations/*.sql (D01 auto-enum, eliminates the
// two-edit ceremony of the prior MIGRATION_NNNN const + applied(N) branch).

use anyhow::Result;
use rusqlite::{params, Connection};
use std::path::PathBuf;
use std::sync::Mutex;

// `MIGRATIONS: &[(i64, &str, &str)]` = (version, stem, sql). Generated by
// build.rs, source of truth is packages/shared-db/migrations/*.sql.
include!(concat!(env!("OUT_DIR"), "/migrations_generated.rs"));

pub struct DbState(pub Mutex<Connection>);

pub fn default_db_path() -> PathBuf {
    // Windows: %APPDATA%\PharmaCarePro\pharmacare.db
    // macOS:   ~/Library/Application Support/PharmaCarePro/pharmacare.db
    // Linux:   ~/.local/share/PharmaCarePro/pharmacare.db
    let base = dirs::data_dir().unwrap_or_else(|| PathBuf::from("."));
    let dir = base.join("PharmaCarePro");
    let _ = std::fs::create_dir_all(&dir);
    dir.join("pharmacare.db")
}

pub fn open_local(path: &std::path::Path) -> Result<Connection> {
    let conn = Connection::open(path)?;
    conn.execute_batch(
        "PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
    )?;
    Ok(conn)
}

pub fn apply_migrations(conn: &Connection) -> Result<()> {
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS _migrations (
            version INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            applied_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
        );",
    )?;
    let applied = |v: i64, c: &Connection| -> bool {
        c.query_row(
            "SELECT COUNT(*) FROM _migrations WHERE version = ?1",
            [v],
            |r| r.get::<_, i64>(0),
        )
        .unwrap_or(0)
            > 0
    };
    for (version, name, sql) in MIGRATIONS {
        if applied(*version, conn) {
            continue;
        }
        conn.execute_batch(sql)?;
        conn.execute(
            "INSERT INTO _migrations (version, name) VALUES (?1, ?2)",
            params![version, name],
        )?;
    }
    ensure_default_shop(conn)?;
    ensure_default_user(conn)?;
    Ok(())
}

/// Seed a default owner user `user_sourav_owner` on fresh installs.
/// A13 (expiry override) needs a known-role actor to gate owner-only overrides.
/// Pilot deployments are single-user (owner), so this is enough; multi-staff
/// deployments add users via an admin screen (future).
///
/// Idempotent: only inserts when `users` is empty.
pub fn ensure_default_user(conn: &Connection) -> Result<()> {
    let count: i64 = conn.query_row("SELECT COUNT(*) FROM users", [], |r| r.get(0))?;
    if count == 0 {
        conn.execute(
            "INSERT INTO users (id, shop_id, name, role, pin_hash, is_active)
             VALUES ('user_sourav_owner', 'shop_local', 'Owner', 'owner', 'seed-no-pin', 1)",
            [],
        )?;
    }
    Ok(())
}

/// Seed a `shop_local` row on fresh installs so FK-bearing tables
/// (oauth_accounts, users, products, etc.) don't crash before the owner
/// has completed first-run setup. The owner overwrites name/gstin/license
/// from the Settings UI on first launch. Values here are placeholders that
/// pass the CHECK constraints (gstin length=15, state_code length=2).
///
/// This is idempotent: only runs when `shops` is empty. Fixes blocker B11
/// in AUDIT_REPORT_2026-04-15.md — the OAuth `gmail_connect` flow inserts
/// into `oauth_accounts(shop_id)` which REFERENCES `shops(id)`.
pub fn ensure_default_shop(conn: &Connection) -> Result<()> {
    let count: i64 = conn.query_row("SELECT COUNT(*) FROM shops", [], |r| r.get(0))?;
    if count == 0 {
        conn.execute(
            "INSERT INTO shops (id, name, gstin, state_code, retail_license, address)
             VALUES ('shop_local', 'My Pharmacy', '00AAAAA0000A0Z0', '00', 'PENDING', 'Please set address in Settings')",
            [],
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// build.rs already enforces contiguous 1..N numbering at compile time,
    /// but a runtime sanity check is cheap and catches hand-edits of the
    /// generated file (or a future include_str! path that mis-enumerates).
    #[test]
    fn migrations_are_contiguous_from_one() {
        assert!(!MIGRATIONS.is_empty(), "no migrations discovered");
        for (i, (version, _, _)) in MIGRATIONS.iter().enumerate() {
            let expected = (i as i64) + 1;
            assert_eq!(
                *version, expected,
                "MIGRATIONS[{i}] has version {version}, expected {expected}"
            );
        }
    }

    /// Every migration must have non-empty SQL so a silent empty file can
    /// never be mistaken for "applied cleanly".
    #[test]
    fn migrations_have_nonempty_sql() {
        for (version, name, sql) in MIGRATIONS {
            assert!(
                !sql.trim().is_empty(),
                "migration {version} ({name}) has empty SQL"
            );
        }
    }

    /// Each migration's stem must start with its 4-digit version prefix. Cheap
    /// second-layer guard against generator bugs.
    #[test]
    fn migration_stems_match_version() {
        for (version, name, _) in MIGRATIONS {
            let prefix = format!("{:04}_", version);
            assert!(
                name.starts_with(&prefix),
                "migration {version} stem {name:?} does not start with {prefix:?}"
            );
        }
    }

    /// End-to-end: apply_migrations against an in-memory SQLite runs the
    /// entire generated chain without error. This is the round-trip gate.
    #[test]
    fn apply_migrations_runs_cleanly_in_memory() {
        let conn = Connection::open_in_memory().expect("open in-memory");
        conn.execute_batch("PRAGMA foreign_keys=ON;")
            .expect("pragma");
        apply_migrations(&conn).expect("apply_migrations");

        // Every migration should have a _migrations row.
        let applied_count: i64 = conn
            .query_row("SELECT COUNT(*) FROM _migrations", [], |r| r.get(0))
            .expect("count _migrations");
        assert_eq!(
            applied_count as usize,
            MIGRATIONS.len(),
            "expected {} migration rows, got {applied_count}",
            MIGRATIONS.len()
        );

        // Re-running must be a no-op (idempotent).
        apply_migrations(&conn).expect("apply_migrations second run");
        let applied_count_2: i64 = conn
            .query_row("SELECT COUNT(*) FROM _migrations", [], |r| r.get(0))
            .expect("count _migrations 2");
        assert_eq!(applied_count, applied_count_2, "second apply should no-op");
    }
}
