// Vitest workspace — tells the root `vitest run` how to discover project
// configs across the monorepo.
// Updated 2026-04-28 — added 26 packages from MASTER_PLAN_v3 + mobile/web apps.
export default [
  "apps/desktop",

  // Existing packages (v2.0 playbook scope)
  "packages/batch-repo",
  "packages/bill-repo",
  "packages/crypto",
  "packages/design-system",
  "packages/directory-repo",
  "packages/einvoice",
  "packages/gmail-grn-bridge",
  "packages/gmail-inbox",
  "packages/grn-repo",
  "packages/gst-engine",
  "packages/gstr1",
  "packages/invoice-print",
  "packages/photo-grn",
  "packages/reports-repo",
  "packages/schedule-h",
  "packages/search-repo",
  "packages/seed-tool",
  "packages/shared-db",
  "packages/sku-images",
  "packages/stock-reconcile",
  "packages/shared-types",

  // NEW packages from MASTER_PLAN_v3 (2026-04-28)
  "packages/auto-update",
  "packages/license",
  "packages/data-export",
  "packages/migration-import",
  "packages/entity-types",
  "packages/ca-export-bundle",
  "packages/share-utils",
  "packages/idempotency",
  "packages/formulary",
  "packages/khata",
  "packages/cash-shift",
  "packages/tally-export",
  "packages/gst-extras",
  "packages/rbac",
  "packages/ocr-rx",
  "packages/demand-forecast",
  "packages/fraud-detection",
  "packages/churn-prediction",
  "packages/counterfeit-shield",
  "packages/ai-copilot",
  "packages/inspector-mode",
  "packages/cold-chain",
  "packages/pmbjp",
  "packages/abdm",
  "packages/dpdp",
  "packages/loyalty",
  "packages/whatsapp-bsp",
  "packages/printer-escpos",
  "packages/cfd-display",
  "packages/ar-shelf",
  "packages/family-vault",
  "packages/plugin-sdk",
  "packages/digital-twin",
];
