// Build script.
//
// 1. tauri_build::build() — wire up Tauri resources, codegen, cargo metadata.
// 2. Auto-enumerate SQL migrations from ../../../packages/shared-db/migrations
//    and emit `$OUT_DIR/migrations_generated.rs` containing the declarative
//    MIGRATIONS array that db.rs include!()s. This eliminates the two-edit
//    ceremony (const + applied(N) branch) that every prior migration needed
//    and has been the single biggest recurring tax in the codebase (D01 in
//    docs/reviews/tech-debt-2026-04-18.md).
//
// Filename convention (enforced by this script — build fails on violation):
//     NNNN_<snake_case_name>.sql       e.g. 0019_fk_indexes.sql
//
// Also enforces: monotonically increasing versions 1, 2, 3, ... with no gaps
// and no duplicates. If a developer renames or deletes a file by mistake, the
// build breaks at compile time rather than producing a silent skip at runtime.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();
    emit_migrations();
}

fn emit_migrations() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // src-tauri -> apps/desktop/src-tauri; migrations live at
    // repo-root/packages/shared-db/migrations. That's four parents up.
    let migrations_dir = manifest_dir
        .join("..")
        .join("..")
        .join("..")
        .join("packages")
        .join("shared-db")
        .join("migrations");
    let migrations_dir = migrations_dir
        .canonicalize()
        .unwrap_or_else(|e| panic!("migrations dir {:?} not found: {e}", migrations_dir));

    // Ask cargo to rebuild when the migrations directory changes.
    println!("cargo:rerun-if-changed={}", migrations_dir.display());

    // Enumerate *.sql files, parse leading 4-digit version, error on any
    // filename that doesn't match convention.
    let mut by_version: BTreeMap<i64, (String, PathBuf)> = BTreeMap::new();
    for entry in fs::read_dir(&migrations_dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", migrations_dir.display()))
    {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        let ext_is_sql = path
            .extension()
            .and_then(|s| s.to_str())
            .map(|s| s.eq_ignore_ascii_case("sql"))
            .unwrap_or(false);
        if !ext_is_sql {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_else(|| panic!("bad filename: {:?}", path));
        let version = parse_version_prefix(stem).unwrap_or_else(|e| {
            panic!(
                "migration filename {:?} violates convention NNNN_name.sql: {e}",
                path
            )
        });
        // Tell cargo to rebuild when any individual migration file changes.
        println!("cargo:rerun-if-changed={}", path.display());
        if let Some(prev) = by_version.insert(version, (stem.to_string(), path.clone())) {
            panic!(
                "duplicate migration version {version}: {:?} and {:?}",
                prev.1, path
            );
        }
    }

    // Validate monotonic 1..N with no gaps.
    let versions: Vec<i64> = by_version.keys().copied().collect();
    for (i, v) in versions.iter().enumerate() {
        let expected = (i as i64) + 1;
        if *v != expected {
            panic!(
                "migration numbering gap: expected {expected}, found {v}. Full sequence: {versions:?}"
            );
        }
    }

    // Build the generated Rust source.
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. Do NOT edit by hand.\n");
    out.push_str("// Source of truth: packages/shared-db/migrations/*.sql\n");
    out.push_str("pub const MIGRATIONS: &[(i64, &str, &str)] = &[\n");
    for (version, (stem, path)) in &by_version {
        // include_str! accepts an absolute path on all platforms.
        out.push_str(&format!(
            "    ({}, \"{}\", include_str!({})),\n",
            version,
            stem,
            literal_str_for_include(path)
        ));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("migrations_generated.rs");
    fs::write(&dest, out).expect("write migrations_generated.rs");
}

/// Parse a migration version prefix like "0001" out of a stem like "0001_init".
fn parse_version_prefix(stem: &str) -> Result<i64, String> {
    let (num, rest) = stem
        .split_once('_')
        .ok_or_else(|| "missing underscore separator".to_string())?;
    if rest.is_empty() {
        return Err("empty name after version prefix".to_string());
    }
    if num.len() != 4 {
        return Err(format!(
            "version prefix must be 4 digits (got {} chars: {:?})",
            num.len(),
            num
        ));
    }
    if !num.chars().all(|c| c.is_ascii_digit()) {
        return Err(format!("version prefix must be digits only: {num:?}"));
    }
    num.parse::<i64>().map_err(|e| e.to_string())
}

/// Render a path as a Rust string literal suitable for `include_str!(...)`.
/// On Windows this must escape backslashes.
fn literal_str_for_include(p: &Path) -> String {
    let mut s = String::from("\"");
    for c in p.display().to_string().chars() {
        match c {
            '\\' => s.push_str("\\\\"),
            '"' => s.push_str("\\\""),
            other => s.push(other),
        }
    }
    s.push('"');
    s
}
