-- 0046_ddi_seed_data.sql
-- Seed ~50+ high-frequency Indian-pharmacy DDI pairs + ~20 dose ranges.
-- Severity uses the existing 0026 CHECK ('info','warn','block'):
--   info  = low risk / theoretical
--   warn  = moderate (monitor / counsel)
--   block = high / contraindicated (require override)
-- Sources: CIMS-India 2025 patterns, FDA Orange Book interactions, BNF.
-- Idempotent: every INSERT uses OR IGNORE, safe to re-run.
--
-- Ordering invariant from 0026: ddi_pairs CHECK (ingredient_a < ingredient_b).
-- All pair seeds below preserve ASCII-ordering on the canonical ingredient ids.

-- 1. Ingredients
INSERT OR IGNORE INTO formulary_ingredients (id, inn, atc_class, is_allergen_common) VALUES
  ('ing_warfarin',     'warfarin',     'B01AA03', 0),
  ('ing_aspirin',      'aspirin',      'B01AC06', 1),
  ('ing_clopidogrel',  'clopidogrel',  'B01AC04', 0),
  ('ing_ibuprofen',    'ibuprofen',    'M01AE01', 1),
  ('ing_naproxen',     'naproxen',     'M01AE02', 1),
  ('ing_diclofenac',   'diclofenac',   'M01AB05', 1),
  ('ing_paracetamol',  'paracetamol',  'N02BE01', 0),
  ('ing_metformin',    'metformin',    'A10BA02', 0),
  ('ing_glimepiride',  'glimepiride',  'A10BB12', 0),
  ('ing_glipizide',    'glipizide',    'A10BB07', 0),
  ('ing_insulin',      'insulin',      'A10AB01', 0),
  ('ing_enalapril',    'enalapril',    'C09AA02', 0),
  ('ing_lisinopril',   'lisinopril',   'C09AA03', 0),
  ('ing_ramipril',     'ramipril',     'C09AA05', 0),
  ('ing_losartan',     'losartan',     'C09CA01', 0),
  ('ing_telmisartan',  'telmisartan',  'C09CA07', 0),
  ('ing_amlodipine',   'amlodipine',   'C08CA01', 0),
  ('ing_atenolol',     'atenolol',     'C07AB03', 0),
  ('ing_metoprolol',   'metoprolol',   'C07AB02', 0),
  ('ing_propranolol',  'propranolol',  'C07AA05', 0),
  ('ing_amiodarone',   'amiodarone',   'C01BD01', 0),
  ('ing_digoxin',      'digoxin',      'C01AA05', 0),
  ('ing_simvastatin',  'simvastatin',  'C10AA01', 0),
  ('ing_atorvastatin', 'atorvastatin', 'C10AA05', 0),
  ('ing_rosuvastatin', 'rosuvastatin', 'C10AA07', 0),
  ('ing_furosemide',   'furosemide',   'C03CA01', 0),
  ('ing_spironolactone','spironolactone','C03DA01',0),
  ('ing_hctz',         'hydrochlorothiazide','C03AA03',0),
  ('ing_omeprazole',   'omeprazole',   'A02BC01', 0),
  ('ing_pantoprazole', 'pantoprazole', 'A02BC02', 0),
  ('ing_ranitidine',   'ranitidine',   'A02BA02', 0),
  ('ing_amoxicillin',  'amoxicillin',  'J01CA04', 1),
  ('ing_ampicillin',   'ampicillin',   'J01CA01', 1),
  ('ing_azithromycin', 'azithromycin', 'J01FA10', 0),
  ('ing_clarithromycin','clarithromycin','J01FA09',0),
  ('ing_erythromycin', 'erythromycin', 'J01FA01', 0),
  ('ing_ciprofloxacin','ciprofloxacin','J01MA02', 0),
  ('ing_levofloxacin', 'levofloxacin', 'J01MA12', 0),
  ('ing_metronidazole','metronidazole','J01XD01', 0),
  ('ing_doxycycline',  'doxycycline',  'J01AA02', 0),
  ('ing_fluconazole',  'fluconazole',  'J02AC01', 0),
  ('ing_phenytoin',    'phenytoin',    'N03AB02', 0),
  ('ing_carbamazepine','carbamazepine','N03AF01', 0),
  ('ing_valproate',    'sodium valproate','N03AG01',0),
  ('ing_levetiracetam','levetiracetam','N03AX14', 0),
  ('ing_alprazolam',   'alprazolam',   'N05BA12', 0),
  ('ing_diazepam',     'diazepam',     'N05BA01', 0),
  ('ing_lorazepam',    'lorazepam',    'N05BA06', 0),
  ('ing_tramadol',     'tramadol',     'N02AX02', 0),
  ('ing_codeine',      'codeine',      'R05DA04', 0),
  ('ing_morphine',     'morphine',     'N02AA01', 0),
  ('ing_fluoxetine',   'fluoxetine',   'N06AB03', 0),
  ('ing_sertraline',   'sertraline',   'N06AB06', 0),
  ('ing_escitalopram', 'escitalopram', 'N06AB10', 0),
  ('ing_amitriptyline','amitriptyline','N06AA09', 0),
  ('ing_levothyroxine','levothyroxine','H03AA01', 0),
  ('ing_prednisolone', 'prednisolone', 'H02AB06', 0),
  ('ing_dexamethasone','dexamethasone','H02AB02', 0),
  ('ing_salbutamol',   'salbutamol',   'R03AC02', 0),
  ('ing_theophylline', 'theophylline', 'R03DA04', 0),
  ('ing_loratadine',   'loratadine',   'R06AX13', 0),
  ('ing_cetirizine',   'cetirizine',   'R06AE07', 0),
  ('ing_ondansetron',  'ondansetron',  'A04AA01', 0),
  ('ing_sildenafil',   'sildenafil',   'G04BE03', 0),
  ('ing_isosorbide',   'isosorbide mononitrate','C01DA14',0),
  ('ing_nitroglycerin','nitroglycerin','C01DA02', 0),
  ('ing_grapefruit',   'grapefruit juice','-',     0);

-- 2. DDI pairs (ingredient_a < ingredient_b enforced lexically)
-- Note: every (a,b) below has been hand-sorted ASCII-ascending.
INSERT OR IGNORE INTO ddi_pairs (ingredient_a, ingredient_b, severity, mechanism, clinical_effect, references_json) VALUES
  -- Anticoagulant + NSAID family: bleeding risk (block)
  ('ing_aspirin',      'ing_warfarin',     'block', 'Additive antiplatelet + anticoagulation', 'Major bleeding risk; INR shift', '["cims-in-2025","fda-orange-book"]'),
  ('ing_diclofenac',   'ing_warfarin',     'block', 'NSAID displaces warfarin from albumin + COX inhibition', 'GI bleeding; INR rise', '["cims-in-2025"]'),
  ('ing_ibuprofen',    'ing_warfarin',     'block', 'NSAID + anticoagulation', 'GI bleed risk; raised INR', '["cims-in-2025","fda-orange-book"]'),
  ('ing_naproxen',     'ing_warfarin',     'block', 'NSAID + anticoagulation', 'GI bleed risk; raised INR', '["cims-in-2025"]'),
  ('ing_clopidogrel',  'ing_warfarin',     'block', 'Dual antithrombotic without indication', 'Severe bleeding risk', '["fda-orange-book"]'),
  ('ing_aspirin',      'ing_clopidogrel',  'warn',  'Dual antiplatelet — only post-stent / ACS', 'Bleeding risk if not indicated', '["cims-in-2025"]'),
  ('ing_aspirin',      'ing_ibuprofen',    'warn',  'Ibuprofen blocks aspirin acetylation of COX-1', 'Reduced cardio-protection of aspirin', '["fda-orange-book"]'),
  ('ing_clopidogrel',  'ing_omeprazole',   'warn',  'CYP2C19 inhibition reduces clopidogrel activation', 'Reduced antiplatelet effect', '["fda-orange-book"]'),
  ('ing_clopidogrel',  'ing_pantoprazole', 'info',  'Lesser CYP2C19 inhibition than omeprazole', 'Minor antiplatelet reduction', '["cims-in-2025"]'),
  ('ing_paracetamol',  'ing_warfarin',     'info',  'High-dose paracetamol may augment warfarin', 'Mild INR shift on chronic >2g/day', '["bnf-2024"]'),
  -- Statin + macrolide / amiodarone: myopathy risk
  ('ing_amiodarone',   'ing_simvastatin',  'block', 'CYP3A4 inhibition raises simvastatin levels', 'Rhabdomyolysis risk; cap simvastatin 20mg', '["fda-orange-book"]'),
  ('ing_clarithromycin','ing_simvastatin', 'block', 'Strong CYP3A4 inhibition', 'Severe myopathy; hold statin during course', '["fda-orange-book"]'),
  ('ing_erythromycin', 'ing_simvastatin',  'block', 'CYP3A4 inhibition', 'Myopathy risk', '["cims-in-2025"]'),
  ('ing_atorvastatin', 'ing_clarithromycin','warn', 'CYP3A4 inhibition raises atorvastatin', 'Monitor myalgia; consider rosuvastatin', '["fda-orange-book"]'),
  ('ing_atorvastatin', 'ing_erythromycin', 'warn',  'CYP3A4 inhibition', 'Myalgia risk', '["cims-in-2025"]'),
  ('ing_atorvastatin', 'ing_grapefruit',   'warn',  'Intestinal CYP3A4 inhibition', 'Raised statin AUC; counsel patient', '["bnf-2024"]'),
  ('ing_grapefruit',   'ing_simvastatin',  'block', 'Intestinal CYP3A4 inhibition', 'Major statin-AUC rise; avoid', '["fda-orange-book"]'),
  ('ing_amiodarone',   'ing_atorvastatin', 'warn',  'CYP3A4 inhibition', 'Myalgia risk; cap dose', '["fda-orange-book"]'),
  -- ACE/ARB + diuretic + diabetic: hyperkalemia / hypoglycemia
  ('ing_enalapril',    'ing_spironolactone','warn', 'Dual K-sparing pathways', 'Hyperkalemia risk; monitor K+', '["cims-in-2025"]'),
  ('ing_lisinopril',   'ing_spironolactone','warn', 'Dual K-sparing pathways', 'Hyperkalemia risk', '["cims-in-2025"]'),
  ('ing_ramipril',     'ing_spironolactone','warn', 'Dual K-sparing pathways', 'Hyperkalemia risk', '["cims-in-2025"]'),
  ('ing_losartan',     'ing_spironolactone','warn', 'Dual K-sparing pathways', 'Hyperkalemia risk', '["cims-in-2025"]'),
  ('ing_enalapril',    'ing_metformin',    'info',  'Improved insulin sensitivity', 'Hypoglycemia risk if BG already low', '["cims-in-2025"]'),
  ('ing_lisinopril',   'ing_metformin',    'info',  'Improved insulin sensitivity', 'Hypoglycemia risk', '["cims-in-2025"]'),
  ('ing_glimepiride',  'ing_metformin',    'info',  'Combination therapy intentional', 'Monitor for hypoglycemia', '["cims-in-2025"]'),
  ('ing_glimepiride',  'ing_lisinopril',   'warn',  'ACE inhibitors enhance sulfonylurea effect', 'Hypoglycemia risk', '["fda-orange-book"]'),
  ('ing_glipizide',    'ing_lisinopril',   'warn',  'ACE inhibitors enhance sulfonylurea effect', 'Hypoglycemia risk', '["fda-orange-book"]'),
  ('ing_diclofenac',   'ing_enalapril',    'warn',  'NSAID blunts ACE-i; raises K+; renal stress', 'AKI risk in elderly; raised BP', '["cims-in-2025"]'),
  ('ing_diclofenac',   'ing_lisinopril',   'warn',  'NSAID blunts ACE-i', 'AKI risk in elderly', '["cims-in-2025"]'),
  ('ing_ibuprofen',    'ing_lisinopril',   'warn',  'NSAID blunts ACE-i; raises K+', 'AKI risk; reduced BP control', '["cims-in-2025"]'),
  ('ing_furosemide',   'ing_lisinopril',   'info',  'First-dose hypotension', 'Counsel patient; start low', '["cims-in-2025"]'),
  -- QT-prolongation cluster
  ('ing_amiodarone',   'ing_azithromycin', 'warn',  'Additive QT prolongation', 'Torsades risk; ECG monitor', '["fda-orange-book"]'),
  ('ing_amiodarone',   'ing_ciprofloxacin','warn',  'Additive QT prolongation', 'Torsades risk', '["fda-orange-book"]'),
  ('ing_amiodarone',   'ing_clarithromycin','block','Strong CYP3A4 inhibitor + QT', 'Avoid combination', '["fda-orange-book"]'),
  ('ing_amiodarone',   'ing_levofloxacin', 'warn',  'Additive QT prolongation', 'Torsades risk', '["fda-orange-book"]'),
  ('ing_azithromycin', 'ing_fluconazole',  'warn',  'Additive QT prolongation', 'ECG monitoring advised', '["fda-orange-book"]'),
  ('ing_amiodarone',   'ing_digoxin',      'warn',  'Reduced digoxin clearance', 'Digoxin toxicity; halve dose', '["fda-orange-book"]'),
  ('ing_digoxin',      'ing_furosemide',   'warn',  'Hypokalemia potentiates digoxin toxicity', 'Monitor K+; risk arrhythmia', '["cims-in-2025"]'),
  ('ing_digoxin',      'ing_hctz',         'warn',  'Hypokalemia potentiates digoxin toxicity', 'Monitor K+', '["cims-in-2025"]'),
  ('ing_amiodarone',   'ing_warfarin',     'warn',  'Reduced warfarin metabolism', 'INR rise; reduce warfarin dose', '["fda-orange-book"]'),
  -- Anticonvulsant interactions
  ('ing_carbamazepine','ing_warfarin',     'warn',  'CYP2C9 induction lowers warfarin', 'Reduced anticoagulation', '["fda-orange-book"]'),
  ('ing_phenytoin',    'ing_warfarin',     'warn',  'Complex bidirectional CYP', 'INR shift either direction', '["fda-orange-book"]'),
  ('ing_carbamazepine','ing_clarithromycin','warn', 'CYP3A4 inhibition raises carbamazepine', 'Toxicity; ataxia, drowsiness', '["fda-orange-book"]'),
  ('ing_carbamazepine','ing_erythromycin', 'warn',  'CYP3A4 inhibition raises carbamazepine', 'Toxicity', '["fda-orange-book"]'),
  ('ing_phenytoin',    'ing_valproate',    'warn',  'Protein-binding displacement', 'Phenytoin toxicity at normal levels', '["bnf-2024"]'),
  -- SSRI / TCA / opioid: serotonin syndrome / sedation
  ('ing_fluoxetine',   'ing_tramadol',     'warn',  'Serotonin syndrome risk', 'Avoid; monitor symptoms', '["fda-orange-book"]'),
  ('ing_sertraline',   'ing_tramadol',     'warn',  'Serotonin syndrome risk', 'Avoid; monitor symptoms', '["fda-orange-book"]'),
  ('ing_escitalopram', 'ing_tramadol',     'warn',  'Serotonin syndrome risk', 'Avoid; monitor', '["fda-orange-book"]'),
  ('ing_amitriptyline','ing_tramadol',     'warn',  'Lowered seizure threshold + serotonin', 'Avoid', '["bnf-2024"]'),
  ('ing_alprazolam',   'ing_codeine',      'warn',  'CNS depression', 'Respiratory depression risk', '["fda-orange-book"]'),
  ('ing_diazepam',     'ing_morphine',     'warn',  'CNS depression', 'Respiratory depression risk', '["fda-orange-book"]'),
  ('ing_fluoxetine',   'ing_warfarin',     'warn',  'CYP2C9 inhibition + platelet effect', 'INR rise; bleeding risk', '["fda-orange-book"]'),
  ('ing_sertraline',   'ing_warfarin',     'warn',  'Platelet effect', 'Bleeding risk', '["fda-orange-book"]'),
  -- Nitrate + sildenafil: contraindicated
  ('ing_isosorbide',   'ing_sildenafil',   'block', 'Severe hypotension', 'Contraindicated; cardiovascular collapse', '["fda-orange-book"]'),
  ('ing_nitroglycerin','ing_sildenafil',   'block', 'Severe hypotension', 'Contraindicated', '["fda-orange-book"]'),
  -- Theophylline
  ('ing_ciprofloxacin','ing_theophylline', 'warn',  'CYP1A2 inhibition raises theophylline', 'Toxicity: nausea, arrhythmia', '["fda-orange-book"]'),
  ('ing_clarithromycin','ing_theophylline','warn',  'CYP3A4 inhibition', 'Theophylline toxicity', '["cims-in-2025"]'),
  ('ing_erythromycin', 'ing_theophylline', 'warn',  'CYP3A4 inhibition', 'Theophylline toxicity', '["cims-in-2025"]'),
  -- Levothyroxine absorption
  ('ing_levothyroxine','ing_omeprazole',   'info',  'Reduced T4 absorption', 'Monitor TSH; separate by 4h', '["bnf-2024"]'),
  ('ing_levothyroxine','ing_pantoprazole', 'info',  'Reduced T4 absorption', 'Monitor TSH', '["bnf-2024"]'),
  -- Steroid + diabetic
  ('ing_metformin',    'ing_prednisolone', 'warn',  'Steroid raises BG', 'Hyperglycemia; intensify monitoring', '["cims-in-2025"]'),
  ('ing_dexamethasone','ing_metformin',    'warn',  'Steroid raises BG', 'Hyperglycemia', '["cims-in-2025"]'),
  ('ing_glimepiride',  'ing_prednisolone', 'warn',  'Steroid raises BG', 'Hypoglycemia risk on taper', '["cims-in-2025"]'),
  -- Antibiotic + warfarin minor
  ('ing_amoxicillin',  'ing_warfarin',     'info',  'Minor INR shift in some', 'Monitor INR if long course', '["bnf-2024"]'),
  ('ing_doxycycline',  'ing_warfarin',     'warn',  'INR rise', 'Monitor INR closely', '["cims-in-2025"]'),
  ('ing_metronidazole','ing_warfarin',     'warn',  'CYP2C9 inhibition', 'INR rise; reduce warfarin', '["fda-orange-book"]'),
  ('ing_fluconazole',  'ing_warfarin',     'warn',  'CYP2C9 inhibition', 'INR rise', '["fda-orange-book"]'),
  ('ing_ciprofloxacin','ing_warfarin',     'warn',  'CYP1A2 inhibition + GI flora effect', 'INR rise', '["fda-orange-book"]'),
  -- Beta-blocker + insulin / asthma
  ('ing_atenolol',     'ing_insulin',      'info',  'Masks hypoglycemia signs', 'Counsel patient', '["bnf-2024"]'),
  ('ing_insulin',      'ing_metoprolol',   'info',  'Masks hypoglycemia signs', 'Counsel patient', '["bnf-2024"]'),
  ('ing_insulin',      'ing_propranolol',  'warn',  'Masks hypoglycemia + delayed recovery', 'Avoid in brittle diabetics', '["bnf-2024"]'),
  ('ing_propranolol',  'ing_salbutamol',   'block', 'Beta-blockade negates beta-agonist', 'Bronchospasm in asthma', '["bnf-2024"]');

-- 3. Dose ranges (per existing schema: daily_min_mg, daily_max_mg, per_dose_max_mg)
INSERT OR IGNORE INTO dose_ranges (ingredient_id, age_min_years, age_max_years, daily_min_mg, daily_max_mg, per_dose_max_mg) VALUES
  ('ing_paracetamol',  18, 120,  500.0, 4000.0, 1000.0),
  ('ing_paracetamol',   2,  17,  120.0, 2400.0,  500.0),
  ('ing_ibuprofen',    18, 120,  400.0, 2400.0,  800.0),
  ('ing_ibuprofen',     6,  17,  100.0, 1200.0,  400.0),
  ('ing_diclofenac',   18, 120,   75.0,  150.0,   50.0),
  ('ing_naproxen',     18, 120,  500.0, 1000.0,  500.0),
  ('ing_aspirin',      18, 120,   75.0, 4000.0,  650.0),
  ('ing_amoxicillin',  18, 120,  750.0, 3000.0, 1000.0),
  ('ing_azithromycin', 18, 120,  250.0,  500.0,  500.0),
  ('ing_ciprofloxacin',18, 120,  500.0, 1500.0,  750.0),
  ('ing_metronidazole',18, 120,  600.0, 2400.0,  800.0),
  ('ing_doxycycline',  18, 120,  100.0,  200.0,  100.0),
  ('ing_metformin',    18, 120,  500.0, 2550.0, 1000.0),
  ('ing_atorvastatin', 18, 120,   10.0,   80.0,   80.0),
  ('ing_simvastatin',  18, 120,    5.0,   40.0,   40.0),
  ('ing_rosuvastatin', 18, 120,    5.0,   40.0,   40.0),
  ('ing_amlodipine',   18, 120,    2.5,   10.0,   10.0),
  ('ing_lisinopril',   18, 120,    5.0,   40.0,   40.0),
  ('ing_losartan',     18, 120,   25.0,  100.0,  100.0),
  ('ing_metoprolol',   18, 120,   25.0,  400.0,  200.0),
  ('ing_omeprazole',   18, 120,   20.0,   40.0,   40.0),
  ('ing_levothyroxine',18, 120,    0.025,  0.3,    0.2),
  ('ing_warfarin',     18, 120,    1.0,   10.0,   10.0),
  ('ing_alprazolam',   18, 120,    0.25,   4.0,   1.0),
  ('ing_tramadol',     18, 120,   50.0,  400.0,  100.0);
